### ISSUE TITLE
Does this work under Rubinius (v2.2.10)?

### ISSUE THREAD

**Issue by n8gard** [thuss/standalone-migrations#102]
It seems to very much not work. If it is not intended to work w/ Rubinius, please let me know and I'll roll my own schema management solution--sadly.

```
palanthas:n8_app nate$ rake db:new_migration name=create_user --trace
rake aborted!
SystemStackError: SystemStackError
kernel/common/string.rb:1572:in `initialize_copy'
kernel/common/kernel.rb:308:in `initialize_dup'
kernel/common/type.rb:437:in `object_initialize_dup'
kernel/bootstrap/string.rb:96:in `dup'
/Users/nate/.rvm/rubies/rbx-2.2.10/library/rubygems/version.rb:159:in `version'
/Users/nate/.rvm/rubies/rbx-2.2.10/library/rubygems/version.rb:328:in `<=>'
kernel/common/comparable.rb:25:in `>='
/Users/nate/.rvm/rubies/rbx-2.2.10/library/rubygems/requirement.rb:18:in `__script__'
kernel/bootstrap/proc.rb:20:in `call'
/Users/nate/.rvm/rubies/rbx-2.2.10/library/rubygems/requirement.rb:228:in `satisfied_by?'
kernel/common/enumerable.rb:304:in `all?'
kernel/bootstrap/array.rb:76:in `each'
kernel/common/enumerable.rb:304:in `all?'
/Users/nate/.rvm/rubies/rbx-2.2.10/library/rubygems/requirement.rb:228:in `satisfied_by?'
/Users/nate/.rvm/rubies/rbx-2.2.10/library/rubygems/dependency.rb:257:in `matching_specs'
kernel/common/enumerable.rb:432:in `find_all'
kernel/bootstrap/array.rb:76:in `each'

# <snip>
```

**Comment by twobitlabs** [comment]
Closing due to the age of this issue.
