### ISSUE TITLE
Loading rake tasks fails when database.yml not present

### ISSUE THREAD

**Issue by malakai97** [thuss/standalone-migrations#117]
Loading the tasks should not be performing any operations.  

Common workarounds are the have a standalone_migrations:environment task that performs the needed operations; from there set the other tasks to require this task.

```
$ bundle exec rake -T
rake aborted!
Cannot load `Rails.application.database_configuration`:
Could not load database configuration. No such file - ["config/database.yml"]
/proj/.bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application/configuration.rb:110:in `database_configuration'
/proj/.bundle/ruby/2.2.0/gems/standalone_migrations-4.0.2/lib/standalone_migrations/configurator.rb:25:in `load_configurations'
/proj/.bundle/ruby/2.2.0/gems/standalone_migrations-4.0.2/lib/standalone_migrations/configurator.rb:31:in `environments_config'
/proj/.bundle/ruby/2.2.0/gems/standalone_migrations-4.0.2/lib/standalone_migrations/tasks.rb:15:in `load_tasks'
/proj/Rakefile:13:in `<top (required)>'
Could not load database configuration. No such file - ["config/database.yml"]
/proj/.bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application/configuration.rb:110:in `database_configuration'
/proj/.bundle/ruby/2.2.0/gems/standalone_migrations-4.0.2/lib/standalone_migrations/configurator.rb:25:in `load_configurations'
/proj/.bundle/ruby/2.2.0/gems/standalone_migrations-4.0.2/lib/standalone_migrations/configurator.rb:31:in `environments_config'
/proj/.bundle/ruby/2.2.0/gems/standalone_migrations-4.0.2/lib/standalone_migrations/tasks.rb:15:in `load_tasks'
/proj/Rakefile:13:in `<top (required)>'
(See full trace by running task with --trace)
```

Rakefile:

``` ruby
$LOAD_PATH.unshift File.expand_path('../lib', __FILE__)
require "standalone_migrations"
StandaloneMigrations::Tasks.load_tasks
```

**Comment by twobitlabs** [comment]
We welcome pull requests (with tests) :+1:

**Comment by twobitlabs** [comment]
Closing due to the age of this issue.
