### ISSUE TITLE
db seeds are not working

### ISSUE THREAD

**Issue by piotrkedzia** [thuss/standalone-migrations#155]
### Steps to reproduce
Run `standalone-migrations` specs

### Expected behavior
All tests green.

### Actual behavior
```
Finished in 53.11 seconds (files took 0.598 seconds to load)
61 examples, 2 failures

Failed examples:

rspec ./spec/standalone_migrations_spec.rb:316 # Standalone migrations db:seed loads
rspec ./spec/standalone_migrations_spec.rb:335 # Standalone migrations db:seed with non-default seed file loads

```

### System configuration
**Ruby version** 2.6.1

### Source of the issue
https://github.com/rails/rails/issues/35782

**Comment by alexandr-shadow** [comment]
Same issue:

`rake aborted!
NoMethodError: undefined method `active_job' for #<Rails::Application::Configuration:0x0000000001c50d40>
/home/shad/.rvm/gems/ruby-2.6.3@tez_tour_hotel_parser/gems/railties-5.2.3/lib/rails/railtie/configuration.rb:97:in `method_missing'
/home/shad/.rvm/gems/ruby-2.6.3@tez_tour_hotel_parser/gems/railties-5.2.3/lib/rails/engine.rb:662:in `with_inline_jobs'
/home/shad/.rvm/gems/ruby-2.6.3@tez_tour_hotel_parser/gems/railties-5.2.3/lib/rails/engine.rb:551:in `load_seed'
/home/shad/.rvm/gems/ruby-2.6.3@tez_tour_hotel_parser/gems/activerecord-5.2.3/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/home/shad/.rvm/gems/ruby-2.6.3@tez_tour_hotel_parser/gems/activerecord-5.2.3/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <top (required)>'
/home/shad/.rvm/gems/ruby-2.6.3@tez_tour_hotel_parser/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/home/shad/.rvm/gems/ruby-2.6.3@tez_tour_hotel_parser/bin/ruby_executable_hooks:24:in `eval'
/home/shad/.rvm/gems/ruby-2.6.3@tez_tour_hotel_parser/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:reset => db:setup => db:seed
(See full trace by running task with --trace)`

**Comment by yantene** [comment]
Adding the following line to Rakefile seems to work correctly.
Is this supposed usage?

```ruby
require 'active_job/railtie'
```
